language: python
python:
  - '3.6'

cache: pip

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxmlsec1-dev pkg-config

install: 'pip install -r requirements.txt -r requirements-dev.txt'

script:
  - flake8
  - isort -c
  - pytest -ra -vvv --cov=.

addons:
  postgresql: '9.6'

after_success: codecov
